- name: Cleanup Virtual GSM Lab Deployment
  hosts: localhost
  gather_facts: no
  vars:
    ssl_verify: false
    server_names:
      - BTS
      - BSC
      - MSC
      - MGW4BSC
      - MGW4MSC
      - HLR
      - STP
      - MS1
      - MS2
  tasks:
    - name: Delete server
      os_server:
        state: absent
        name: "{{ item }}"
      loop: "{{ server_names }}"

    - name: Delete keypair gsm_admin_key
      os_keypair:
        state: absent
        name: gsm_admin_key

    - name: Delete security group rules for gsm-security-group
      os_security_group_rule:
        state: absent
        security_group: gsm-security-group.management

    - name: Delete security group gsm-security-group
      os_security_group:
        state: absent
        name: gsm-security-group

    - name: Delete router gsm-router
      os_router:
        state: absent
        name: gsm-router

    - name: Delete subnet gsm-subnet.private
      os_subnet:
        state: absent
        name: gsm-subnet.private

    - name: Delete network gsm-network.private
      os_network:
        state: absent
        name: gsm-network.private

    - name: Delete image gsm-image.ubuntu-22.04
      os_image:
        state: absent
        name: gsm-image.ubuntu-22.04

    - name: Delete flavor m1.medium
      os_nova_flavor:
        state: absent
        name: m1.medium

    - name: Remove tmp directory
      file:
        path: ./tmp
        state: absent
        recurse: yes
        force: yes