- name: Cleanup Virtual GSM Lab Deployment
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Delete server
      os_server:
        state: absent
        name: BTS

    - name: Delete keypair
      os_keypair:
        state: absent
        name: gsm_admin_key

    - name: Delete security group rules
      os_security_group_rule:
        state: absent
        security_group: gsm-security-group.management

    - name: Delete security group
      os_security_group:
        state: absent
        name: gsm-security-group

    - name: Delete router
      os_router:
        state: absent
        name: gsm-router

    - name: Delete subnet
      os_subnet:
        state: absent
        name: gsm-subnet.private

    - name: Delete network
      os_network:
        state: absent
        name: gsm-network.private

    - name: Delete image
      os_image:
        state: absent
        name: gsm-image.ubuntu-22.04

    - name: Delete flavor
      os_nova_flavor:
        state: absent
        name: gsm-flavor.medium

    - name: Remove tmp directory
      file:
        path: /tmp/gsm
        state: absent
        recurse: yes
        force: yes